# Generated by Django 4.1.6 on 2024-07-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_starting_bid_listing_current_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='user',
            new_name='bidding_user',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='bid',
            new_name='new_bid',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='listing_user',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='current_bid',
            new_name='starting_bid',
        ),
    ]
