# Generated by Django 4.2.14 on 2024-07-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='comments',
            field=models.JSONField(default=list),
        ),
    ]
